Repository SymfonyCasts/reset-password-bundle, pull requests merged in 2020-12, with the labels that each got.

#134 Allow installation with PHP8, add Symfony 5.2 to tests
  .github/workflows/ci.yml
  composer.json
  tests/FunctionalTests/Persistence/ResetPasswordRequestRepositoryTest.php
Labels: status: reviewed

#137 add PHP 8 support in CI / dev environments
  .github/workflows/ci.yml
  composer.json
  phpunit.xml.dist
  psalm.xml
Labels: CI

#135 improve token expiration
  CHANGELOG.md
  composer.json
  src/Exception/GeneratedAtNotSetException.php
  src/Model/ResetPasswordToken.php
  src/ResetPasswordHelper.php
  src/Resources/translations/ResetPasswordBundle.en.xlf
  tests/UnitTests/Model/ResetPasswordTokenTest.php
Labels: bug, enhancement, status: needs review

#139 revert unintended default UTC tz on expiresAt
  src/ResetPasswordHelper.php
  tests/UnitTests/ResetPasswordHelperTest.php
Labels: status: needs review
