Repository SymfonyCasts/reset-password-bundle, pull requests merged in 2022-07, with the labels that each got.

#229 Add catalan translations
  src/Resources/translations/ResetPasswordBundle.ca.xlf
Labels: status: reviewed, Feature

#231 [ci] global flex is not needed
  .github/workflows/ci.yml
Labels: status: needs review, Minor

#233 [git-released] v1.14.0
  CHANGELOG.md
Labels: Minor
