Repository SymfonyCasts/reset-password-bundle, pull requests merged in 2022-09, with the labels that each got.

#239 [ci] fix docblock separation
  src/Generator/ResetPasswordRandomGenerator.php
  src/Generator/ResetPasswordTokenGenerator.php
  src/Model/ResetPasswordTokenComponents.php
  src/Util/ResetPasswordCleaner.php
  tests/Fixtures/Entity/ResetPasswordTestFixtureRequest.php
  tests/Fixtures/Entity/ResetPasswordTestFixtureUser.php
Labels: Minor

#235 fix expiration diff bug in php 8.1
  composer.json
Labels: Bug

#237 drop symfony 4.4 support
  composer.json
  src/Command/ResetPasswordRemoveExpiredCommand.php
  tests/ResetPasswordTestKernel.php
Labels: Status: Reviewed, Feature

#245 [translations] add additional Polish translations and fix pluralizations
  src/Resources/translations/ResetPasswordBundle.pl.xlf
Labels: Feature

#242 [translations] Additional German translations
  src/Resources/translations/ResetPasswordBundle.de.xlf
Labels: Feature
